import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import styles from "./page.module.css";
import SideBox from "@/components/SideBox";
import ProviderCom from "@/components/Provider";
import InitRecent from "./util/InitRecent";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <html lang="ko">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <ProviderCom>
                    <InitRecent/>
                    <Header />
                        <main className={styles.main} >
                            <div className={styles.contentBox}>
                                {children}
                            </div>
                            <SideBox />
                        </main>
                    <Footer />
                </ProviderCom>
            </body>
        </html>
    );
}
